version: "3"
services:
  app:
    image: qanda/app:latest
    build:
      context: ./docker/php
    volumes:
      - .:/work:cached
      - ./.git
      - ./storage/logs/php:/var/log/php:delegated
    environment:
      - TZ=Asia/Tokyo

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./public:/work/public:cached
      - ./.git
      - ./storage/logs/nginx:/var/log/nginx:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:5.7
    volumes:
      - db-store:/var/lib/mysql:delegated
      - ./storage/logs/db:/var/log/mysql:delegated
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${DB_PORT}:3306

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379:6379

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  db-store:
